### PR TITLE
add mrunner

### PR DESCRIPTION
**Pull request by BartekCupial**

### CODE REVIEW

**Comment by BartekCupial** [comment]
* by deafult binding to /ttyrecs is required in mrunner.yaml
* turned off hydra changing the directory, mrunner does this
* added gitignore in root dir, when running mrunner locally we want to exclude the experiment wandb etc
* added cheat sheet for running mrunner

**Comment by BartekCupial** [comment]
I'd say that train.sh and run_athena, run_ares, run_gmum shouldn't be used and are depreciated. For now I won't delete them, maybe they are still useful.

**Comment by maciejwolczyk** [comment]
Thanks, looks good! 

> by deafult binding to /ttyrecs is required in mrunner.yaml
Cool! I wonder if there's a nice way to share the mrunner configurations... The easiest thing would probably be to share it on Slack for now? Or maybe we could add an example `mrunner.yaml` file to the repository?

> added gitignore in root dir, when running mrunner locally we want to exclude the experiment wandb etc
Just to make sure, we do this to avoid uploading these files and directories to the computing server? I'm not sure if mrunner looks at `.gitignore` to decide what to upload.

**Comment by BartekCupial** [comment]
> Just to make sure, we do this to avoid uploading these files and directories to the computing server? I'm not sure if mrunner looks at .gitignore to decide what to upload.
Uploading doesn't happen because mrunner is uploading only `experiment_code` directory. And those files are stored in root. I've added .gitignore just for git.
> Cool! I wonder if there's a nice way to share the mrunner configurations... The easiest thing would probably be to share it on Slack for now? Or maybe we could add an example mrunner.yaml file to the repository?
I've shared in on slack, we shouldn't share it in public repo.

**Pull request merged**
